### ISSUE TITLE
Ukrainian/Russian text is empty

### ISSUE THREAD

**Issue by otimoshc** [jamesinglis/ew61-export#2]
I tried using the Ukrainian/Russian codec encoding to convert my EW database to text and the text files only show empty spaces and commas/periods. I have a mix of English/Russian/Ukrainian songs and the Russian/Ukrainian songs don't get encoded correctly. Im not a python guy, but do you know why Im getting this?

**Comment by jamesinglis** [comment]
Apologies for the late response - this problem has come up a few times with different languages using a non-Latin alphabet. Are the English songs also displaying as garbled characters?

This may be a good use case for me to test - feel free to send your database files to hello@jamesinglis.no and I'll see if I can recreate/resolve the problem.
