### ISSUE TITLE
Missing propresenter6_slide_text.txt?

### ISSUE THREAD

**Issue by jeremybphillips** [jamesinglis/ew61-export#3]
Hello.

Line 454 in functions.php tries to read in '/resources/propresenter6_slide_text.txt' but it looks like the file isn't in the resources directory. Do you have copy that you could push to the repo?

Thanks!

**Comment by jamesinglis** [comment]
Sorry for the late reply on this - I've just added this file into the repo and pushed an incremental version (0.3.1).
